version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container-new
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: market
    ports:
      - "5432:5432"
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    networks:
      - mynetwork

  app:
    build: .
    container_name: my-python-app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres  # Postgres service name as host
      DB_NAME: market
      DB_USER: postgres
      DB_PASS: mysecretpassword
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "80:5000"  # Map Flask's 5000 port to host's 80 port
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
